name: peoples_speech
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.7
  - numpy
  - matplotlib
  - conda-forge::datasets
  - conda-forge::librosa
  - pyyaml=5.4.1
  - spyder-kernels=2.4
  - pip
  - pip:
    - soundfile
